"""add pricing and rules tables

Revision ID: f3c6424e8bb3
Revises: 5c8b1742d39b
Create Date: 2026-09-08 07:43:40.646342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c6424e8bb3'
down_revision: Union[str, Sequence[str], None] = '5c8b1742d39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('combination_type', sa.Enum('COMBINE', 'OVERRIDE', 'STOP', name='rulecombinationtype'), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_end_date'), 'pricing_rules', ['end_date'], unique=False)
    op.create_index(op.f('ix_pricing_rules_is_active'), 'pricing_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_pricing_rules_name'), 'pricing_rules', ['name'], unique=False)
    op.create_index(op.f('ix_pricing_rules_priority'), 'pricing_rules', ['priority'], unique=False)
    op.create_index(op.f('ix_pricing_rules_start_date'), 'pricing_rules', ['start_date'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_purchase', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('maximum_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotions_code'), 'promotions', ['code'], unique=True)
    op.create_index(op.f('ix_promotions_expiry_date'), 'promotions', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_promotions_is_active'), 'promotions', ['is_active'], unique=False)
    op.create_index(op.f('ix_promotions_start_date'), 'promotions', ['start_date'], unique=False)
    op.create_table('rule_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('PERCENTAGE_DISCOUNT', 'FIXED_DISCOUNT', 'ADDITIONAL_CHARGE', 'TAX', name='ruleactiontype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['pricing_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_actions_action_type'), 'rule_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_rule_actions_rule_id'), 'rule_actions', ['rule_id'], unique=False)
    op.create_table('rule_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.Enum('EQUALS', 'NOT_EQUALS', 'GREATER_THAN', 'GREATER_THAN_OR_EQUAL', 'LESS_THAN', 'LESS_THAN_OR_EQUAL', 'CONTAINS', 'NOT_CONTAINS', 'IN', 'NOT_IN', name='conditionoperator'), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('condition_group', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['pricing_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_conditions_field'), 'rule_conditions', ['field'], unique=False)
    op.create_index(op.f('ix_rule_conditions_rule_id'), 'rule_conditions', ['rule_id'], unique=False)
    op.create_table('pricing_calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('promotion_code', sa.String(length=50), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('additional_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('input_parameters', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_calculations_calculated_at'), 'pricing_calculations', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_pricing_calculations_customer_id'), 'pricing_calculations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_pricing_calculations_product_id'), 'pricing_calculations', ['product_id'], unique=False)
    op.create_index(op.f('ix_pricing_calculations_promotion_code'), 'pricing_calculations', ['promotion_code'], unique=False)
    op.create_table('calculation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['pricing_calculations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['pricing_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_rules_calculation_id'), 'calculation_rules', ['calculation_id'], unique=False)
    op.create_index(op.f('ix_calculation_rules_rule_id'), 'calculation_rules', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculation_rules_rule_id'), table_name='calculation_rules')
    op.drop_index(op.f('ix_calculation_rules_calculation_id'), table_name='calculation_rules')
    op.drop_table('calculation_rules')
    op.drop_index(op.f('ix_pricing_calculations_promotion_code'), table_name='pricing_calculations')
    op.drop_index(op.f('ix_pricing_calculations_product_id'), table_name='pricing_calculations')
    op.drop_index(op.f('ix_pricing_calculations_customer_id'), table_name='pricing_calculations')
    op.drop_index(op.f('ix_pricing_calculations_calculated_at'), table_name='pricing_calculations')
    op.drop_table('pricing_calculations')
    op.drop_index(op.f('ix_rule_conditions_rule_id'), table_name='rule_conditions')
    op.drop_index(op.f('ix_rule_conditions_field'), table_name='rule_conditions')
    op.drop_table('rule_conditions')
    op.drop_index(op.f('ix_rule_actions_rule_id'), table_name='rule_actions')
    op.drop_index(op.f('ix_rule_actions_action_type'), table_name='rule_actions')
    op.drop_table('rule_actions')
    op.drop_index(op.f('ix_promotions_start_date'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_is_active'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_expiry_date'), table_name='promotions')
    op.drop_index(op.f('ix_promotions_code'), table_name='promotions')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_pricing_rules_start_date'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_priority'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_name'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_is_active'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_end_date'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    # ### end Alembic commands ###
